package cn.sut.oodtime.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNotification<M extends BaseNotification<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setNotifDetails(java.lang.String notifDetails) {
		set("notif_details", notifDetails);
		return (M)this;
	}

	public java.lang.String getNotifDetails() {
		return get("notif_details");
	}

	public M setSort(java.lang.String sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.String getSort() {
		return get("sort");
	}
	
	public M setNoSend(java.lang.Integer isSend) {
		set("no_send", isSend);
		return (M)this;
	}

	public java.lang.Integer getNoSend() {
		return get("no_send");
	}

}
