package cn.sut.oodtime.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPhotoPath(java.lang.String photoPath) {
		set("photo_path", photoPath);
		return (M)this;
	}

	public java.lang.String getPhotoPath() {
		return get("photo_path");
	}

	public M setPersonalProfile(java.lang.String personalProfile) {
		set("personal_profile", personalProfile);
		return (M)this;
	}

	public java.lang.String getPersonalProfile() {
		return get("personal_profile");
	}

	public M setReputationValue(java.lang.Integer reputationValue) {
		set("reputation_value", reputationValue);
		return (M)this;
	}

	public java.lang.Integer getReputationValue() {
		return get("reputation_value");
	}

	public M setAvailableTime(java.lang.String availableTime) {
		set("available_time", availableTime);
		return (M)this;
	}

	public java.lang.String getAvailableTime() {
		return get("available_time");
	}

	public M setSkills(java.lang.String skills) {
		set("skills", skills);
		return (M)this;
	}

	public java.lang.String getSkills() {
		return get("skills");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setBirthday(java.lang.String birthday) {
		set("birthday", birthday);
		return (M)this;
	}

	public java.lang.String getBirthday() {
		return get("birthday");
	}

	public M setJob(java.lang.String job) {
		set("job", job);
		return (M)this;
	}

	public java.lang.String getJob() {
		return get("job");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public M setSalt(java.lang.String salt) {
		set("salt", salt);
		return (M)this;
	}

	public java.lang.String getSalt() {
		return get("salt");
	}

	public M setTokenKey(java.lang.String tokenKey) {
		set("tokenKey", tokenKey);
		return (M)this;
	}

	public java.lang.String getTokenKey() {
		return get("tokenKey");
	}

	public M setTokenTime(java.util.Date tokenTime) {
		set("tokenTime", tokenTime);
		return (M)this;
	}

	public java.util.Date getTokenTime() {
		return get("tokenTime");
	}

	public M setLoginTime(java.util.Date loginTime) {
		set("loginTime", loginTime);
		return (M)this;
	}

	public java.util.Date getLoginTime() {
		return get("loginTime");
	}

}
