package cn.sut.oodtime.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
		return (M)this;
	}

	public java.lang.String getTaskName() {
		return get("task_name");
	}

	public M setRewardAmount(java.lang.String rewardAmount) {
		set("reward_amount", rewardAmount);
		return (M)this;
	}

	public java.lang.String getRewardAmount() {
		return get("reward_amount");
	}

	public M setTimeConsuming(java.lang.String timeConsuming) {
		set("time_consuming", timeConsuming);
		return (M)this;
	}

	public java.lang.String getTimeConsuming() {
		return get("time_consuming");
	}

	public M setTaskDetails(java.lang.String taskDetails) {
		set("task_details", taskDetails);
		return (M)this;
	}

	public java.lang.String getTaskDetails() {
		return get("task_details");
	}

	public M setPhotoPath(java.lang.String photoPath) {
		set("photo_path", photoPath);
		return (M)this;
	}

	public java.lang.String getPhotoPath() {
		return get("photo_path");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
