package cn.sut.oodtime.common.model;

import cn.sut.oodtime.common.model.base.BaseNotification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notification extends BaseNotification<Notification> {
	public static final Notification dao = new Notification().dao();
}
