package cn.sut.oodtime.common.model;

import cn.sut.oodtime.common.model.base.BaseRelationship;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Relationship extends BaseRelationship<Relationship> {
	public static final Relationship dao = new Relationship().dao();
}
